import "./globals.css";
import { Noto_Sans_JP } from 'next/font/google'

const notoJp = Noto_Sans_JP({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={notoJp.className}>{children}</body>
    </html>
  )
}
